### ISSUE TITLE
game crashes when using magnesium and tetra are installed together

### ISSUE THREAD

**Issue by 301Gabe** [Someone-Else-Was-Taken/Periodic-Table-Reforged#72]
whenever I put a netherite sword in a workbench or check advancements the game crashes. In the case of the netherite sword crash it also makes the world I was playing on unusable.

**Comment by viceversagames** [comment]
You need to post a crash log, I'm not crashing with Tetra. 

![image](https://user-images.githubusercontent.com/67132971/140631829-fa4a5602-4f0b-4517-bb7d-6b0d378933db.png)

**Comment by 301Gabe** [comment]
[crash-2021-11-07_09.01.24-client.txt]
does that work?

**Comment by 301Gabe** [comment]
how do I do that without putting down a large wall of text?

**Comment by 301Gabe** [comment]
Hello? Can I get a response?

**Comment by Someone-Else-Was-Taken** [comment]
> Hello? Can I please get a response?

Hello, I was unable to recreate this issue on my end. Putting a Netherite Sword into the Workbench and using Netherite to upgrade it functioned on my end. The same is true with checking advancements. 
This may either have been resolved in a more recent update or may be a mod incompatibility.

**Comment by 301Gabe** [comment]
Well I don't know why it doesn't happen on your end, because it still happens to me even when tetra and magnesium are the only mods loaded. What version are you testing this on?
